# Generated by Django 4.2.3 on 2023-09-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='email',
            field=models.EmailField(default='satish@gmail.com', max_length=254),
        ),
    ]
